sensors:
  - sensor_plugin: occupancy_map_monitor/LidarOctomapUpdater
    scan_topic: /chest_lidar/scan
    max_range: 5.0
    point_subsample: 1
    padding_offset: 0.07
    padding_scale: 1.0
    filtered_cloud_topic: filtered_cloud
