# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  l_ankle_pitch:
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: false
    max_acceleration: 0
  l_ankle_roll:
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: false
    max_acceleration: 0
  l_elbow:
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: false
    max_acceleration: 0
  l_hip_pitch:
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: false
    max_acceleration: 0
  l_hip_roll:
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: false
    max_acceleration: 0
  l_hip_yaw:
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: false
    max_acceleration: 0
  l_knee:
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: false
    max_acceleration: 0
  l_shoulder_pitch:
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: false
    max_acceleration: 0
  l_shoulder_roll:
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: false
    max_acceleration: 0
  l_shoulder_yaw:
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: false
    max_acceleration: 0
  l_wrist_roll:
    has_velocity_limits: true
    max_velocity: 1.4
    has_acceleration_limits: false
    max_acceleration: 0
  l_wrist_yaw1:
    has_velocity_limits: true
    max_velocity: 1.4
    has_acceleration_limits: false
    max_acceleration: 0
  l_wrist_yaw2:
    has_velocity_limits: true
    max_velocity: 1.4
    has_acceleration_limits: false
    max_acceleration: 0
  r_ankle_pitch:
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: false
    max_acceleration: 0
  r_ankle_roll:
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: false
    max_acceleration: 0
  r_elbow:
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: false
    max_acceleration: 0
  r_hip_pitch:
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: false
    max_acceleration: 0
  r_hip_roll:
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: false
    max_acceleration: 0
  r_hip_yaw:
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: false
    max_acceleration: 0
  r_knee:
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: false
    max_acceleration: 0
  r_shoulder_pitch:
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: false
    max_acceleration: 0
  r_shoulder_roll:
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: false
    max_acceleration: 0
  r_shoulder_yaw:
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: false
    max_acceleration: 0
  r_wrist_roll:
    has_velocity_limits: true
    max_velocity: 1.4
    has_acceleration_limits: false
    max_acceleration: 0
  r_wrist_yaw1:
    has_velocity_limits: true
    max_velocity: 1.4
    has_acceleration_limits: false
    max_acceleration: 0
  r_wrist_yaw2:
    has_velocity_limits: true
    max_velocity: 1.4
    has_acceleration_limits: false
    max_acceleration: 0